server:
  port: 9001
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud
    username: root
    password: 13435219863
  application:
    name: user-sever
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: cn.itcast.user.pojo
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka


logging:
  level:
    com.itcast: debug

test: admin
